// Removed from the site on 9 Oct 2026. Original source: see backup/kitchen/README.md

const SERVICE_KITCHEN: Service = {
  slug: "modular-kitchens",
  n: "02",
  title: "Modular Kitchens",
  short: "Made-to-measure kitchens built around how you cook, store and live.",
  long: "Moisture-resistant kitchens built around how your family cooks, stores and lives. Every carcass is cut and edge-banded in our Sambhar workshop and fitted by our own team.",
  includes: [
    "Modular cabinets & drawers",
    "Premium shutters & finishes",
    "Chimney, hob & accessories",
    "Plumbing & electrical integration",
  ],
  priceChip: "From ₹1,350/sq.ft",
  gradePrices: { standard: "₹1,350/sq.ft", premium: "₹2,000/sq.ft", luxury: "₹2,590/sq.ft" },
  image: "svc-kitchen",
  heroImage: "kitchen-teal-hero",
  headlineLead: "Modular kitchens built around how",
  headlineEm: "your family cooks.",
  heroSub:
    "Moisture-resistant BWP plywood, premium hardware and in-house installation for kitchens that last.",
  heroPrimary: "Get my kitchen estimate",
  heroSecondary: "WhatsApp a photo of your kitchen",
  factChips: [
    { label: "From ₹1,350/sq.ft", sub: "Standard grade", icon: "IndianRupee" },
    { label: "Free site visit", sub: "in Sambhar, Nawa, Jaipur", icon: "MapPin" },
    { label: "Hardware warranty", sub: "Up to 10 years", icon: "ShieldCheck" },
  ],
  callouts: [
    { label: "BWP marine plywood carcass", x: 22, y: 34 },
    { label: "Soft-close hinges & tandem drawers", x: 74, y: 78 },
    { label: "Profile-lit wall units", x: 70, y: 22 },
  ],
  lightsToggle: false,
  options: {
    kind: "layout",
    label: "Choose your kitchen layout",
    moreLabel: "View more layouts",
    items: [
      {
        id: "l-shaped",
        label: "L-shaped",
        icon: "Columns2",
        drawing: "plan-l-shaped",
        dimensions: ["3040 mm", "2440 mm"],
        image: "layout-photo",
        bestFor: [
          "Most common and versatile",
          "Works well in Indian homes",
          "Good for small to medium spaces",
          "Keeps cooking, cleaning and storage close",
        ],
      },
      {
        id: "u-shaped",
        label: "U-shaped",
        icon: "Columns3",
        drawing: "plan-l-shaped",
        dimensions: ["3350 mm", "2740 mm"],
        image: "kitchen-gallery-2",
        bestFor: [
          "Maximum counter and storage space",
          "Ideal for large families who cook a lot",
          "Needs a room at least 2.4 m wide",
          "Separate zones for prep, cooking and washing",
        ],
      },
      {
        id: "parallel",
        label: "Parallel",
        icon: "Rows2",
        drawing: "plan-l-shaped",
        dimensions: ["3660 mm", "2130 mm"],
        image: "kitchen-gallery-3",
        bestFor: [
          "Narrow kitchens with doors at both ends",
          "Efficient two-wall work triangle",
          "Common in Jaipur apartments",
          "Easy to keep wet and dry sides apart",
        ],
      },
      {
        id: "straight",
        label: "Straight",
        icon: "Rows3",
        drawing: "plan-l-shaped",
        dimensions: ["3050 mm", "600 mm"],
        image: "kitchen-gallery-4",
        bestFor: [
          "Compact 1BHK and studio kitchens",
          "Open-plan living and dining areas",
          "Lowest cost per running foot",
          "Tall units add storage on one wall",
        ],
      },
      {
        id: "island",
        label: "Island",
        icon: "LayoutGrid",
        drawing: "plan-l-shaped",
        dimensions: ["4270 mm", "3660 mm"],
        image: "kitchen-gallery-1",
        bestFor: [
          "Large open kitchens and villas",
          "Extra prep space and breakfast seating",
          "A social kitchen for entertaining",
          "Needs about 1 m of walking space all round",
        ],
      },
    ],
  },
  finishes: {
    caption: "Tap a finish to preview it on the kitchen.",
    previewImage: "finish-preview",
    previewLabel: "Petrol Teal matte with copper handles",
    groups: [
      {
        id: "shutter",
        label: "Shutter Finish",
        swatches: [
          { id: "petrol-teal", label: "Petrol Teal", hex: "#1F5F63", sub: "Matte laminate" },
          { id: "sage", label: "Sage Green", hex: "#8FA694", sub: "Matte laminate" },
          { id: "walnut", label: "Walnut Veneer", hex: "#6B4428", sub: "Wood finish" },
          { id: "ivory", label: "Ivory Acrylic", hex: "#EFE9DC", sub: "High-gloss" },
          { id: "graphite", label: "Graphite", hex: "#3B3F41", sub: "PU finish" },
        ],
      },
      {
        id: "handle",
        label: "Handle Finish",
        swatches: [
          { id: "copper", label: "Copper", hex: "#B87333", sub: "Bar handle" },
          { id: "brass", label: "Brass", hex: "#C9A24B", sub: "Bar handle" },
          { id: "black", label: "Matte Black", hex: "#1E1E1E", sub: "Bar handle" },
          { id: "handleless", label: "Handle-less", hex: "#D9D4C8", sub: "Profile" },
        ],
      },
    ],
  },
  fixChips: null,
  inside: {
    eyebrow: "Inside every Shivansh kitchen",
    title: "Built to perform, inside and out.",
    text: "Quality materials, proper detailing and expert installation in every kitchen.",
    image: "cabinet-inside",
  },
  hotspots: [
    {
      n: 1,
      title: "18 mm BWP plywood carcass",
      text: "Moisture-resistant and durable.",
      x: 28,
      y: 14,
    },
    {
      n: 2,
      title: "Sealed edge-banding",
      text: "Protects from moisture and gives a clean finish.",
      x: 68,
      y: 48,
    },
    { n: 3, title: "Soft-close hinges", text: "Smooth, quiet and long-lasting.", x: 86, y: 66 },
    {
      n: 4,
      title: "Tandem drawer systems",
      text: "Easy access and high load-bearing.",
      x: 36,
      y: 70,
    },
    {
      n: 5,
      title: "Corner pull-outs",
      text: "Makes the most of every inch of space.",
      x: 14,
      y: 86,
    },
  ],
  materials: [
    {
      name: "BWP Marine Plywood",
      note: "Moisture-resistant and long lasting.",
      image: "board-bwp",
    },
    {
      name: "Matte / Acrylic Finish",
      note: "Wide range of colours and finishes.",
      image: "mat-teal-laminate",
    },
    {
      name: "Quartz / Marble-look",
      note: "Durable, easy to clean and elegant.",
      image: "mat-marble",
    },
    { name: "Soft-close Hardware", note: "Hinges and tandem drawers.", image: "mat-hinge" },
    {
      name: "Accessories",
      note: "Corner pull-outs, organizers and more.",
      image: "cabinet-inside",
    },
  ],
  gradeRows: [
    {
      grade: "standard",
      name: "Standard",
      from: "₹1,350/sq.ft",
      bullets: ["MR grade plywood", "Matte laminates", "Standard fittings", "1 year warranty"],
      recommended: false,
    },
    {
      grade: "premium",
      name: "Premium",
      from: "₹2,000/sq.ft",
      bullets: [
        "BWP waterproof plywood",
        "Acrylic / high-gloss finishes",
        "Soft-close hardware",
        "5 years warranty",
      ],
      recommended: true,
    },
    {
      grade: "luxury",
      name: "Luxury",
      from: "₹2,590/sq.ft",
      bullets: [
        "HDHMR / Boilo",
        "PU / veneer finish",
        "Blum / Hettich hardware",
        "10 years warranty",
      ],
      recommended: false,
    },
  ],
  gallery: [
    "kitchen-gallery-1",
    "kitchen-gallery-2",
    "kitchen-gallery-3",
    "kitchen-gallery-4",
    "kitchen-gallery-5",
    "gallery-handle-detail",
  ],
  galleryLabel: "Kitchen gallery",
  galleryLink: { label: "View all kitchens", to: "/projects?category=kitchens" },
  caseStudySlug: "teal-copper-kitchen",
  caseStudyQuote: {
    text: "Shivansh understood how we cook and designed a kitchen that is both beautiful and practical.",
    name: "Priya Sharma",
    town: "Sambhar, Rajasthan",
  },
  faqs: [
    SHARED_FAQ_SITE_VISIT,
    {
      q: "How long does a modular kitchen take?",
      a: "A typical 100–150 sq.ft kitchen takes 4–6 weeks from design sign-off: about three weeks of manufacturing in our workshop and one to two weeks of installation on site.",
    },
    {
      q: "Do you give a written warranty?",
      a: "Yes. Every quotation lists the warranty for each item: 1 year at Standard, 5 years at Premium and 10 years at Luxury on branded hardware, plus our own workmanship guarantee.",
    },
    {
      q: "Can you work with my existing platform?",
      a: "Yes. If your granite or marble platform is level and in good condition, we build the base units to fit it. If it needs replacing, we quote that separately so you can decide.",
    },
    {
      q: "Do you handle electrical and lighting too?",
      a: "Yes. Chimney, hob, socket points and under-cabinet profile lights are planned in the drawing and wired before the units go in, so nothing is cut or patched later.",
    },
  ],
  stickyBar: {
    label: "Kitchen · 120 sq.ft · Premium",
    note: "≈ ₹2.08 – 2.36 lakh",
    sub: "(indicative range)",
    primary: "Send on WhatsApp",
    secondary: "Adjust",
  },
  quickEstimate: { space: "kitchen", area: 120, grade: "premium" },
  related: ["wardrobes-storage", "false-ceiling-lighting", "wall-panelling-flooring"],
};

