// Product catalogue: the boards, finishes, hardware, modules and surfaces Shivansh builds with.
// Prices are indicative 2026 dealer/installed rates for the Jaipur region, excluding GST, and
// should be confirmed by the client before launch (see PLACEHOLDERS.md).

import type { ImageKey } from "./image-keys";
import type { SpaceId } from "./pricing";

export type CatalogueCategoryId =
  | "kitchens"
  | "wardrobes"
  | "boards"
  | "finishes"
  | "hardware"
  | "panels-floors"
  | "ceilings-lighting"
  | "countertops";

export type CatalogueCategory = {
  id: CatalogueCategoryId;
  label: string;
  /** lucide-react export name. */
  icon: string;
  blurb: string;
};

export const CATALOGUE_CATEGORIES: CatalogueCategory[] = [
  {
    id: "kitchens",
    label: "Kitchen modules",
    icon: "CookingPot",
    blurb: "Base, wall and tall units, islands and the accessories that go inside them.",
  },
  {
    id: "wardrobes",
    label: "Wardrobes",
    icon: "DoorClosed",
    blurb: "Hinged, sliding and walk-in wardrobes with lofts and organised interiors.",
  },
  {
    id: "boards",
    label: "Boards",
    icon: "Layers",
    blurb: "The carcass behind every shutter: MR, BWP marine, HDHMR and Boilo.",
  },
  {
    id: "finishes",
    label: "Shutter finishes",
    icon: "Palette",
    blurb: "Laminate, membrane, acrylic, veneer and PU paint.",
  },
  {
    id: "hardware",
    label: "Hardware",
    icon: "Wrench",
    blurb: "Hinges, drawer systems, lift-ups, sliding channels and handles.",
  },
  {
    id: "panels-floors",
    label: "Wall panels & floors",
    icon: "PanelsTopLeft",
    blurb: "WPC fluted panels, wooden louvres, wallpaper, vinyl and wooden flooring.",
  },
  {
    id: "ceilings-lighting",
    label: "Ceilings & lighting",
    icon: "Lightbulb",
    blurb: "POP, gypsum and designer ceilings with cove, profile and spot lighting.",
  },
  {
    id: "countertops",
    label: "Countertops",
    icon: "Square",
    blurb: "Granite, marble and quartz counters, cut and polished on site.",
  },
];

export type CatalogueTag = "Recommended" | "Waterproof" | "Budget" | "Premium" | "Popular";

export const CATALOGUE_TAGS: CatalogueTag[] = [
  "Recommended",
  "Popular",
  "Waterproof",
  "Budget",
  "Premium",
];

export type PriceUnit = "per sq.ft" | "per rft" | "per sheet" | "per pair" | "per set" | "each";

export type Product = {
  id: string;
  category: CatalogueCategoryId;
  name: string;
  tagline: string;
  /** Three short specification lines. */
  specs: [string, string, string];
  priceFrom: number;
  priceTo?: number;
  unit: PriceUnit;
  /** What the unit refers to, e.g. "installed, cabinet area". */
  priceNote?: string;
  brands?: string;
  warranty?: string;
  leadTime: string;
  image: ImageKey;
  tags: CatalogueTag[];
  /** Estimator space this product feeds into. */
  estimatorSpace?: SpaceId;
};

export const PRODUCTS: Product[] = [
  /* ---------------------------------------------------------------- kitchens */
  {
    id: "base-unit",
    category: "kitchens",
    name: "Base units",
    tagline: "Drawers, shutters and sink units below the counter.",
    specs: [
      "600 mm deep, 850 mm high",
      "18 mm carcass, 2 mm PVC edge",
      "Soft-close drawers optional",
    ],
    priceFrom: 4200,
    priceTo: 6500,
    unit: "per rft",
    priceNote: "installed, Standard to Premium",
    leadTime: "3–4 weeks",
    warranty: "5 years on hardware",
    image: "cat-base-unit",
    tags: ["Popular"],
    estimatorSpace: "kitchen",
  },
  {
    id: "wall-unit",
    category: "kitchens",
    name: "Wall units",
    tagline: "Overhead storage with lift-up or hinged shutters.",
    specs: [
      "350 mm deep, 600–720 mm high",
      "Profile light under the unit",
      "Glass or solid shutters",
    ],
    priceFrom: 3200,
    priceTo: 4800,
    unit: "per rft",
    priceNote: "installed",
    leadTime: "3–4 weeks",
    image: "cat-wall-unit",
    tags: [],
    estimatorSpace: "kitchen",
  },
  {
    id: "tall-unit",
    category: "kitchens",
    name: "Tall & pantry units",
    tagline: "Floor-to-ceiling storage for groceries, oven and fridge housing.",
    specs: ["2,100–2,400 mm high", "Pull-out pantry baskets", "Built-in oven or microwave niche"],
    priceFrom: 7500,
    priceTo: 11000,
    unit: "per rft",
    priceNote: "installed",
    leadTime: "3–4 weeks",
    image: "cat-tall-unit",
    tags: ["Premium"],
    estimatorSpace: "kitchen",
  },
  {
    id: "island",
    category: "kitchens",
    name: "Island unit",
    tagline: "A 6 ft island with counter, drawers and a breakfast ledge.",
    specs: [
      "1,800 × 900 mm",
      "Counter and shutters matched to the kitchen",
      "Optional hob or sink",
    ],
    priceFrom: 48000,
    unit: "per set",
    priceNote: "installed, excluding counter stone upgrade",
    leadTime: "4 weeks",
    image: "render-3d",
    tags: ["Premium"],
    estimatorSpace: "kitchen",
  },
  {
    id: "accessories-basic",
    category: "kitchens",
    name: "Accessory set · Basic",
    tagline: "Cutlery tray and a bottle pull-out.",
    specs: ["SS cutlery tray", "Bottle pull-out, 150 mm", "Fits any base unit"],
    priceFrom: 9000,
    unit: "per set",
    leadTime: "In stock",
    brands: "Ebco, Ozone",
    image: "cat-tandem-drawer",
    tags: ["Budget"],
    estimatorSpace: "kitchen",
  },
  {
    id: "accessories-standard",
    category: "kitchens",
    name: "Accessory set · Standard",
    tagline: "Basic set plus a corner carousel and tall pantry baskets.",
    specs: ["Corner carousel or D-tray", "Pantry pull-out, 4 baskets", "Plate and thali racks"],
    priceFrom: 32000,
    unit: "per set",
    leadTime: "1–2 weeks",
    brands: "Hettich, Hafele",
    image: "cabinet-inside",
    tags: ["Recommended", "Popular"],
    estimatorSpace: "kitchen",
  },
  {
    id: "accessories-full",
    category: "kitchens",
    name: "Accessory set · Full",
    tagline: "Magic corner, tandem baskets and wicker units.",
    specs: ["Magic corner unit", "Tandem baskets on every drawer", "Wicker and oil pull-outs"],
    priceFrom: 68000,
    unit: "per set",
    leadTime: "2–3 weeks",
    brands: "Blum, Hettich",
    image: "cabinet-inside",
    tags: ["Premium"],
    estimatorSpace: "kitchen",
  },
  /* --------------------------------------------------------------- wardrobes */
  {
    id: "hinged-wardrobe",
    category: "wardrobes",
    name: "Hinged wardrobe",
    tagline: "Classic swing shutters, the most storage for the money.",
    specs: [
      "600 mm deep, up to 2,400 mm high",
      "Shelves, hanging rail and drawers",
      "Any shutter finish",
    ],
    priceFrom: 1550,
    priceTo: 3140,
    unit: "per sq.ft",
    priceNote: "shutter area, installed",
    leadTime: "3 weeks",
    warranty: "5 years on hardware",
    image: "grid-bedroom",
    tags: ["Popular", "Budget"],
    estimatorSpace: "wardrobe",
  },
  {
    id: "sliding-wardrobe",
    category: "wardrobes",
    name: "Sliding wardrobe",
    tagline: "Space-saving shutters that glide on soft-close tracks.",
    specs: ["Two or three shutters", "Soft-close dampers", "Mirror or glass inserts optional"],
    priceFrom: 1900,
    priceTo: 3500,
    unit: "per sq.ft",
    priceNote: "shutter area, installed",
    leadTime: "3–4 weeks",
    brands: "Hettich, Hafele",
    image: "cat-sliding-channel",
    tags: ["Recommended"],
    estimatorSpace: "wardrobe",
  },
  {
    id: "loft",
    category: "wardrobes",
    name: "Loft unit",
    tagline: "Storage above the wardrobe, up to the ceiling.",
    specs: ["Laminate shutters", "Lift-up or hinged", "Matched to the wardrobe below"],
    priceFrom: 1070,
    unit: "per sq.ft",
    priceNote: "shutter area, installed",
    leadTime: "With the wardrobe",
    image: "cat-loft",
    tags: ["Budget"],
    estimatorSpace: "wardrobe",
  },
  {
    id: "walk-in",
    category: "wardrobes",
    name: "Walk-in wardrobe",
    tagline: "Open shelving, drawers and lighting in a dressing room.",
    specs: [
      "Open or glass-shutter modules",
      "Profile lighting on every shelf",
      "Dressing table and mirror",
    ],
    priceFrom: 2200,
    priceTo: 3800,
    unit: "per sq.ft",
    priceNote: "module area, installed",
    leadTime: "4–5 weeks",
    image: "cat-walk-in",
    tags: ["Premium"],
    estimatorSpace: "wardrobe",
  },
  /* ------------------------------------------------------------------ boards */
  {
    id: "mr-plywood",
    category: "boards",
    name: "MR plywood",
    tagline: "Moisture-resistant plywood for dry areas.",
    specs: ["18 mm, 8 × 4 ft, IS 303", "Wardrobes, TV units, study tables", "Hardwood core"],
    priceFrom: 2400,
    priceTo: 3200,
    unit: "per sheet",
    leadTime: "In stock",
    brands: "Century, Greenply, Kitply",
    image: "board-mr",
    tags: ["Budget"],
  },
  {
    id: "bwp-plywood",
    category: "boards",
    name: "BWP marine plywood",
    tagline: "Boiling-water-proof plywood for kitchens and wet areas.",
    specs: [
      "18 mm, 8 × 4 ft, IS 710",
      "Phenolic resin, borer-proof",
      "Kitchens, bathrooms, utility",
    ],
    priceFrom: 3800,
    priceTo: 5600,
    unit: "per sheet",
    leadTime: "In stock",
    brands: "Century Sainik 710, Greenply Ecotec, Archidply",
    warranty: "Up to lifetime (manufacturer)",
    image: "board-bwp",
    tags: ["Recommended", "Waterproof"],
  },
  {
    id: "hdhmr",
    category: "boards",
    name: "HDHMR board",
    tagline: "Dense, smooth board for PU paint and routed shutters.",
    specs: [
      "18 mm, 8 × 4 ft",
      "High-density, moisture-resistant",
      "Best surface for PU and membrane",
    ],
    priceFrom: 2900,
    priceTo: 3600,
    unit: "per sheet",
    leadTime: "In stock",
    brands: "Action Tesa, Greenpanel",
    image: "board-hdhmr",
    tags: ["Premium"],
  },
  {
    id: "boilo",
    category: "boards",
    name: "Boilo board",
    tagline: "Waterproof engineered board for refined shutters.",
    specs: ["18 mm, 8 × 4 ft", "Boiling-water-resistant", "Kitchen shutters, bathroom vanities"],
    priceFrom: 3400,
    priceTo: 4200,
    unit: "per sheet",
    leadTime: "1 week",
    brands: "Action Tesa",
    image: "board-boilo",
    tags: ["Waterproof"],
  },
  /* ---------------------------------------------------------------- finishes */
  {
    id: "laminate",
    category: "finishes",
    name: "Laminate",
    tagline: "Hard-wearing, hundreds of colours and textures.",
    specs: [
      "1 mm high-pressure laminate",
      "Matte, textured, suede or gloss",
      "Easy to repair and replace",
    ],
    priceFrom: 1100,
    priceTo: 2400,
    unit: "per sheet",
    priceNote: "8 × 4 ft; ₹430/sq.ft applied",
    leadTime: "In stock",
    brands: "Merino, Greenlam, Century",
    image: "cat-laminate-sheets",
    tags: ["Budget", "Popular"],
  },
  {
    id: "membrane",
    category: "finishes",
    name: "Membrane (PVC foil)",
    tagline: "Seamless wrap over routed shutters, no visible edges.",
    specs: ["Vacuum-pressed on HDHMR", "Grooved and classic profiles", "Matte or soft-gloss"],
    priceFrom: 600,
    unit: "per sq.ft",
    priceNote: "shutter area, applied",
    leadTime: "2 weeks",
    image: "cat-membrane",
    tags: [],
  },
  {
    id: "acrylic",
    category: "finishes",
    name: "Acrylic (high gloss)",
    tagline: "Mirror-like shutters that wipe clean.",
    specs: [
      "1 mm acrylic sheet on BWP/HDHMR",
      "Scratch-resistant, UV stable",
      "Colour-matched edge bands",
    ],
    priceFrom: 4500,
    priceTo: 7500,
    unit: "per sheet",
    priceNote: "8 × 4 ft; ₹820/sq.ft applied",
    leadTime: "1–2 weeks",
    brands: "Senosan, Rehau, Merino",
    image: "cat-acrylic",
    tags: ["Recommended", "Popular"],
  },
  {
    id: "veneer",
    category: "finishes",
    name: "Natural veneer",
    tagline: "Real wood grain, polished on site.",
    specs: ["Teak, walnut, oak, ash", "Matte PU polish", "Book-matched panels on request"],
    priceFrom: 3500,
    priceTo: 6500,
    unit: "per sheet",
    priceNote: "8 × 4 ft; ₹1,000/sq.ft applied",
    leadTime: "2–3 weeks",
    image: "cat-veneer",
    tags: ["Premium"],
  },
  {
    id: "pu-paint",
    category: "finishes",
    name: "PU paint",
    tagline: "Any colour, matte or gloss, with no edges at all.",
    specs: [
      "Sprayed polyurethane on HDHMR",
      "Handle-less profiles possible",
      "Colour-matched to any swatch",
    ],
    priceFrom: 1150,
    unit: "per sq.ft",
    priceNote: "shutter area, applied",
    leadTime: "3 weeks",
    image: "cat-pu",
    tags: ["Premium"],
  },
  /* ---------------------------------------------------------------- hardware */
  {
    id: "hinge-standard",
    category: "hardware",
    name: "Soft-close hinge · Standard",
    tagline: "Reliable Indian soft-close hinges for wardrobes and units.",
    specs: ["110° clip-on", "Soft-close integrated", "Nickel-plated steel"],
    priceFrom: 140,
    priceTo: 220,
    unit: "per pair",
    leadTime: "In stock",
    brands: "Ebco, Ozone",
    warranty: "2 years",
    image: "mat-hinge",
    tags: ["Budget"],
  },
  {
    id: "hinge-hettich",
    category: "hardware",
    name: "Soft-close hinge · Hettich / Hafele",
    tagline: "German-engineered hinges with 80,000-cycle testing.",
    specs: ["Sensys / Metalla 110°", "Integrated Silent System", "3-D adjustable"],
    priceFrom: 380,
    priceTo: 520,
    unit: "per pair",
    leadTime: "In stock",
    brands: "Hettich, Hafele",
    warranty: "5 years",
    image: "ws-hardware",
    tags: ["Recommended", "Popular"],
  },
  {
    id: "hinge-blum",
    category: "hardware",
    name: "Soft-close hinge · Blum",
    tagline: "Austrian hinges with a lifetime manufacturer warranty.",
    specs: ["Clip top Blumotion 110°", "200,000-cycle tested", "Tool-free assembly"],
    priceFrom: 650,
    priceTo: 900,
    unit: "per pair",
    leadTime: "1 week",
    brands: "Blum",
    warranty: "Lifetime (manufacturer)",
    image: "mat-hinge",
    tags: ["Premium"],
  },
  {
    id: "tandem-drawer",
    category: "hardware",
    name: "Tandem drawer system",
    tagline: "Full-extension drawers that carry 30–40 kg silently.",
    specs: ["Full extension, soft-close", "30–40 kg load rating", "Steel sides, 450–500 mm"],
    priceFrom: 3200,
    priceTo: 8000,
    unit: "per set",
    priceNote: "Hettich InnoTech to Blum Tandembox",
    leadTime: "In stock",
    brands: "Hettich, Blum",
    image: "cat-tandem-drawer",
    tags: ["Popular"],
  },
  {
    id: "lift-up",
    category: "hardware",
    name: "Lift-up fitting",
    tagline: "Wall units and lofts that open upwards and stay open.",
    specs: ["Aventos-type lift", "Stays at any angle", "For shutters 300–900 mm high"],
    priceFrom: 6000,
    priceTo: 12000,
    unit: "per set",
    leadTime: "1 week",
    brands: "Blum Aventos, Hettich Lift Advanced",
    image: "cat-lift-up",
    tags: ["Premium"],
  },
  {
    id: "sliding-channel",
    category: "hardware",
    name: "Sliding wardrobe channel",
    tagline: "Top-hung track with rollers and soft-close dampers.",
    specs: ["For 2–3 shutters up to 80 kg", "Soft-close both ends", "Aluminium track"],
    priceFrom: 2200,
    priceTo: 3800,
    unit: "per set",
    leadTime: "In stock",
    brands: "Hettich TopLine, Hafele",
    image: "cat-sliding-channel",
    tags: [],
  },
  {
    id: "handles",
    category: "hardware",
    name: "Handles & profiles",
    tagline: "Copper, brass, matte black bars and handle-less G-profiles.",
    specs: ["Bar handles 128–320 mm", "Aluminium G / J profiles per rft", "Finish-matched screws"],
    priceFrom: 350,
    priceTo: 900,
    unit: "each",
    priceNote: "profiles ₹450 per rft",
    leadTime: "In stock",
    image: "cat-handles",
    tags: ["Popular"],
  },
  /* ------------------------------------------------------------ panels-floors */
  {
    id: "wpc-panel",
    category: "panels-floors",
    name: "WPC fluted panels",
    tagline: "Waterproof fluted panels for TV walls and wet areas.",
    specs: ["2,900 × 160 mm slats", "Termite- and water-proof", "Wood-grain or solid colours"],
    priceFrom: 260,
    unit: "per sq.ft",
    priceNote: "material; +₹40 installation",
    leadTime: "In stock",
    image: "journal-wpc",
    tags: ["Recommended", "Waterproof"],
    estimatorSpace: "panelling",
  },
  {
    id: "louvres",
    category: "panels-floors",
    name: "Wooden louvres",
    tagline: "Warm slat walls in veneer or solid wood.",
    specs: [
      "20–60 mm slats, felt or MDF backing",
      "Teak, walnut, oak finishes",
      "Acoustic backing optional",
    ],
    priceFrom: 420,
    unit: "per sq.ft",
    priceNote: "material; +₹40 installation",
    leadTime: "2 weeks",
    image: "living-slat-panel",
    tags: ["Premium"],
    estimatorSpace: "panelling",
  },
  {
    id: "laminate-panel",
    category: "panels-floors",
    name: "Laminate wall panels",
    tagline: "Flat or grooved laminate panelling for feature walls.",
    specs: ["8 mm MDF with laminate", "Grooved or flush joints", "Any laminate colour"],
    priceFrom: 220,
    unit: "per sq.ft",
    priceNote: "material; +₹40 installation",
    leadTime: "1 week",
    image: "grid-fluted-tv",
    tags: ["Budget"],
    estimatorSpace: "panelling",
  },
  {
    id: "wallpaper",
    category: "panels-floors",
    name: "Wallpaper",
    tagline: "Washable vinyl wallpapers, imported and Indian.",
    specs: ["Vinyl on non-woven backing", "Washable, 10-year colourfast", "Murals on request"],
    priceFrom: 95,
    unit: "per sq.ft",
    priceNote: "material; +₹40 installation",
    leadTime: "1 week",
    image: "cat-wallpaper",
    tags: ["Budget"],
    estimatorSpace: "panelling",
  },
  {
    id: "vinyl-floor",
    category: "panels-floors",
    name: "Vinyl (SPC) flooring",
    tagline: "Waterproof click planks for homes and shops.",
    specs: ["4–5 mm SPC core", "Click-lock, no adhesive", "Wood and stone looks"],
    priceFrom: 115,
    unit: "per sq.ft",
    priceNote: "material; +₹40 installation",
    leadTime: "1 week",
    image: "cat-vinyl-floor",
    tags: ["Waterproof", "Budget"],
    estimatorSpace: "panelling",
  },
  {
    id: "laminate-floor",
    category: "panels-floors",
    name: "Laminate wood flooring",
    tagline: "AC4 laminate planks for bedrooms and living rooms.",
    specs: ["8 mm HDF core, AC4", "Click-lock with underlay", "Oak, walnut, ash decors"],
    priceFrom: 190,
    unit: "per sq.ft",
    priceNote: "material; +₹40 installation",
    leadTime: "1 week",
    image: "cat-laminate-floor",
    tags: ["Popular"],
    estimatorSpace: "panelling",
  },
  {
    id: "engineered-floor",
    category: "panels-floors",
    name: "Engineered wood flooring",
    tagline: "Real oak top layer for living rooms and villas.",
    specs: ["3–4 mm oak wear layer", "14 mm engineered core", "Brushed and oiled finish"],
    priceFrom: 420,
    unit: "per sq.ft",
    priceNote: "material; +₹40 installation",
    leadTime: "2–3 weeks",
    image: "cat-engineered-floor",
    tags: ["Premium"],
    estimatorSpace: "panelling",
  },
  /* -------------------------------------------------------- ceilings-lighting */
  {
    id: "pop-ceiling",
    category: "ceilings-lighting",
    name: "POP false ceiling",
    tagline: "Plaster-of-Paris ceilings with curved coves.",
    specs: [
      "Gypsum POP on GI framing",
      "Curves and mouldings possible",
      "Painted, ready for lights",
    ],
    priceFrom: 85,
    unit: "per sq.ft",
    priceNote: "installed and painted",
    leadTime: "1–2 weeks",
    image: "cat-pop-ceiling",
    tags: ["Budget"],
    estimatorSpace: "ceiling",
  },
  {
    id: "gypsum-ceiling",
    category: "ceilings-lighting",
    name: "Gypsum false ceiling",
    tagline: "Board ceilings with taped joints, quick and crack-resistant.",
    specs: ["12.5 mm Gyproc board", "GI channel framing", "Moisture-resistant board for wet rooms"],
    priceFrom: 105,
    unit: "per sq.ft",
    priceNote: "installed and painted",
    leadTime: "1 week",
    brands: "Saint-Gobain Gyproc",
    image: "svc-ceiling",
    tags: ["Recommended", "Popular"],
    estimatorSpace: "ceiling",
  },
  {
    id: "designer-ceiling",
    category: "ceilings-lighting",
    name: "Designer ceiling",
    tagline: "Multi-level, floating and wooden-rafter ceilings.",
    specs: ["Two or more levels", "Wooden rafters or louvres", "Integrated profile lighting"],
    priceFrom: 160,
    unit: "per sq.ft",
    priceNote: "installed and painted",
    leadTime: "2–3 weeks",
    image: "cat-designer-ceiling",
    tags: ["Premium"],
    estimatorSpace: "ceiling",
  },
  {
    id: "cove-strip",
    category: "ceilings-lighting",
    name: "LED cove strip",
    tagline: "Warm strip light hidden in the ceiling cove.",
    specs: ["2700–3000 K warm white", "12 V, 9.6 W per metre", "Driver included"],
    priceFrom: 140,
    unit: "per rft",
    priceNote: "fitted and wired",
    leadTime: "In stock",
    image: "journal-cove",
    tags: ["Popular"],
    estimatorSpace: "ceiling",
  },
  {
    id: "profile-light",
    category: "ceilings-lighting",
    name: "Aluminium profile lights",
    tagline: "Continuous COB lines with a diffused finish.",
    specs: ["Recessed aluminium profile", "COB strip, no dots", "Dimmable option"],
    priceFrom: 260,
    unit: "per rft",
    priceNote: "fitted and wired",
    leadTime: "1 week",
    image: "cat-profile-light",
    tags: ["Premium"],
    estimatorSpace: "ceiling",
  },
  {
    id: "spotlight",
    category: "ceilings-lighting",
    name: "Spotlights",
    tagline: "Recessed COB spots, fitted and wired.",
    specs: ["7–12 W COB", "Warm or neutral white", "Standard to premium fixtures"],
    priceFrom: 450,
    priceTo: 750,
    unit: "each",
    priceNote: "fitted and wired",
    leadTime: "In stock",
    image: "grid-cove-ceiling",
    tags: [],
    estimatorSpace: "ceiling",
  },
  /* -------------------------------------------------------------- countertops */
  {
    id: "granite",
    category: "countertops",
    name: "Granite",
    tagline: "Hard-wearing natural stone in black, brown and grey.",
    specs: ["18–20 mm slabs", "Polished with nosing", "Heat and scratch resistant"],
    priceFrom: 350,
    unit: "per sq.ft",
    priceNote: "installed",
    leadTime: "1 week",
    image: "gallery-kitchen-a",
    tags: ["Budget", "Popular"],
    estimatorSpace: "kitchen",
  },
  {
    id: "marble",
    category: "countertops",
    name: "Marble",
    tagline: "Italian and Makrana marble for statement counters.",
    specs: ["18–20 mm slabs", "Sealed against stains", "Book-matched on request"],
    priceFrom: 750,
    unit: "per sq.ft",
    priceNote: "installed",
    leadTime: "2 weeks",
    image: "mat-marble",
    tags: ["Premium"],
    estimatorSpace: "kitchen",
  },
  {
    id: "quartz",
    category: "countertops",
    name: "Quartz",
    tagline: "Engineered stone: stain-proof, seamless and consistent.",
    specs: ["20 mm slabs", "Non-porous, no sealing", "Marble-look and solid colours"],
    priceFrom: 900,
    unit: "per sq.ft",
    priceNote: "installed",
    leadTime: "2 weeks",
    brands: "Kalinga, Caesarstone",
    image: "cat-quartz",
    tags: ["Recommended"],
    estimatorSpace: "kitchen",
  },
];

export function productsIn(category: CatalogueCategoryId): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getCategory(id: string): CatalogueCategory | undefined {
  return CATALOGUE_CATEGORIES.find((c) => c.id === id);
}

export const CATALOGUE_PAGE = {
  eyebrow: "Product catalogue",
  headlineLead: "Everything we build with,",
  headlineEm: "priced honestly.",
  sub: "Boards, finishes, hardware and surfaces we install every week, with the indicative rates behind our estimates. Every item can be seen and touched at the Sambhar workshop.",
  searchPlaceholder: "Search boards, finishes, brands…",
  allLabel: "All products",
  askLabel: "Ask on WhatsApp",
  estimateLabel: "Estimate",
  fromLabel: "From",
  emptyTitle: "Nothing matches that search.",
  emptyText: "Try another word, or ask us on WhatsApp and we will find it.",
  pricesTitle: "How to read these prices",
  prices: [
    "All rates exclude 18% GST. The estimator adds GST for you.",
    "Cabinet work is priced per sq.ft of shutter area, the industry standard, not floor area.",
    "Ranges run from Standard to Premium grade; brand, colour and site conditions move the final figure.",
    "Boards and finishes are quoted per sheet for reference; in a project they are built into the per-sq.ft rate.",
  ],
  cta: {
    eyebrow: "See it before you choose",
    titleLead: "Touch every sample",
    titleEm: "at the workshop.",
    text: "Bring your floor plan. We will lay out boards, shutters and hardware side by side and price your rooms on the spot.",
    primary: "Book a workshop visit",
    secondary: "Chat on WhatsApp",
  },
} as const;
