// Generated by tools/gen-images.py from the asset manifest. Do not edit by hand.
export type ImageKey =
  | "hero-living"
  | "pill-wood"
  | "pill-handle"
  | "blueprint-kitchen"
  | "kitchen-island-finished"
  | "testimonial-room"
  | "featured-living"
  | "grid-kitchen"
  | "grid-bedroom"
  | "grid-office"
  | "grid-cove-ceiling"
  | "grid-fluted-tv"
  | "grid-ivory-kitchen"
  | "grid-kids-room"
  | "grid-boutique"
  | "grid-pooja"
  | "kitchen-teal-hero"
  | "kitchen-before"
  | "kitchen-after"
  | "floor-plan"
  | "render-3d"
  | "elevation"
  | "mat-teal-laminate"
  | "mat-bwp-plywood"
  | "mat-copper-handle"
  | "mat-marble"
  | "mat-hinge"
  | "gallery-kitchen-wide"
  | "gallery-kitchen-a"
  | "gallery-kitchen-b"
  | "gallery-handle-detail"
  | "next-bedroom"
  | "iso-home"
  | "svc-complete-home"
  | "svc-kitchen"
  | "svc-wardrobes"
  | "svc-ceiling"
  | "svc-panelling"
  | "svc-renovation"
  | "grade-standard"
  | "grade-premium"
  | "grade-luxury"
  | "cabinet-inside"
  | "plan-l-shaped"
  | "layout-photo"
  | "finish-preview"
  | "kitchen-gallery-1"
  | "kitchen-gallery-2"
  | "kitchen-gallery-3"
  | "kitchen-gallery-4"
  | "kitchen-gallery-5"
  | "wardrobe-elevation"
  | "process-measure"
  | "board-mr"
  | "board-bwp"
  | "board-hdhmr"
  | "board-boilo"
  | "founder-portrait"
  | "tl-2014"
  | "tl-2017"
  | "tl-2020"
  | "tl-2023"
  | "tl-today"
  | "ws-panel-saw"
  | "ws-edge-banding"
  | "ws-hardware"
  | "ws-laminate"
  | "ws-install"
  | "team-1"
  | "team-2"
  | "team-3"
  | "team-4"
  | "team-5"
  | "est-standard"
  | "est-premium"
  | "est-luxury"
  | "workshop-exterior"
  | "living-slat-panel"
  | "bedroom-modern"
  | "sketch-plant-left"
  | "sketch-arch-right"
  | "journal-kitchen-featured"
  | "journal-plywood"
  | "journal-ceiling"
  | "journal-wardrobe-finish"
  | "journal-workshop"
  | "journal-wpc"
  | "journal-cove"
  | "avatar-dinesh"
  | "plywood-hero"
  | "sketch-plant-404"
  | "sketch-ladder-404"
  | "sketch-room-404"
  | "cat-base-unit"
  | "cat-wall-unit"
  | "cat-tall-unit"
  | "cat-laminate-sheets"
  | "cat-acrylic"
  | "cat-membrane"
  | "cat-veneer"
  | "cat-pu"
  | "cat-tandem-drawer"
  | "cat-lift-up"
  | "cat-sliding-channel"
  | "cat-handles"
  | "cat-walk-in"
  | "cat-loft"
  | "cat-wallpaper"
  | "cat-vinyl-floor"
  | "cat-laminate-floor"
  | "cat-engineered-floor"
  | "cat-pop-ceiling"
  | "cat-designer-ceiling"
  | "cat-profile-light"
  | "cat-quartz"
  | "orig-hero-living"
  | "orig-work-kitchen"
  | "orig-work-bedroom"
  | "orig-work-office"
  | "orig-craft"
  | "brand-monogram"
  | "brand-logo";

export const IMAGE_KEYS: ImageKey[] = [
  "hero-living",
  "pill-wood",
  "pill-handle",
  "blueprint-kitchen",
  "kitchen-island-finished",
  "testimonial-room",
  "featured-living",
  "grid-kitchen",
  "grid-bedroom",
  "grid-office",
  "grid-cove-ceiling",
  "grid-fluted-tv",
  "grid-ivory-kitchen",
  "grid-kids-room",
  "grid-boutique",
  "grid-pooja",
  "kitchen-teal-hero",
  "kitchen-before",
  "kitchen-after",
  "floor-plan",
  "render-3d",
  "elevation",
  "mat-teal-laminate",
  "mat-bwp-plywood",
  "mat-copper-handle",
  "mat-marble",
  "mat-hinge",
  "gallery-kitchen-wide",
  "gallery-kitchen-a",
  "gallery-kitchen-b",
  "gallery-handle-detail",
  "next-bedroom",
  "iso-home",
  "svc-complete-home",
  "svc-kitchen",
  "svc-wardrobes",
  "svc-ceiling",
  "svc-panelling",
  "svc-renovation",
  "grade-standard",
  "grade-premium",
  "grade-luxury",
  "cabinet-inside",
  "plan-l-shaped",
  "layout-photo",
  "finish-preview",
  "kitchen-gallery-1",
  "kitchen-gallery-2",
  "kitchen-gallery-3",
  "kitchen-gallery-4",
  "kitchen-gallery-5",
  "wardrobe-elevation",
  "process-measure",
  "board-mr",
  "board-bwp",
  "board-hdhmr",
  "board-boilo",
  "founder-portrait",
  "tl-2014",
  "tl-2017",
  "tl-2020",
  "tl-2023",
  "tl-today",
  "ws-panel-saw",
  "ws-edge-banding",
  "ws-hardware",
  "ws-laminate",
  "ws-install",
  "team-1",
  "team-2",
  "team-3",
  "team-4",
  "team-5",
  "est-standard",
  "est-premium",
  "est-luxury",
  "workshop-exterior",
  "living-slat-panel",
  "bedroom-modern",
  "sketch-plant-left",
  "sketch-arch-right",
  "journal-kitchen-featured",
  "journal-plywood",
  "journal-ceiling",
  "journal-wardrobe-finish",
  "journal-workshop",
  "journal-wpc",
  "journal-cove",
  "avatar-dinesh",
  "plywood-hero",
  "sketch-plant-404",
  "sketch-ladder-404",
  "sketch-room-404",
  "cat-base-unit",
  "cat-wall-unit",
  "cat-tall-unit",
  "cat-laminate-sheets",
  "cat-acrylic",
  "cat-membrane",
  "cat-veneer",
  "cat-pu",
  "cat-tandem-drawer",
  "cat-lift-up",
  "cat-sliding-channel",
  "cat-handles",
  "cat-walk-in",
  "cat-loft",
  "cat-wallpaper",
  "cat-vinyl-floor",
  "cat-laminate-floor",
  "cat-engineered-floor",
  "cat-pop-ceiling",
  "cat-designer-ceiling",
  "cat-profile-light",
  "cat-quartz",
  "orig-hero-living",
  "orig-work-kitchen",
  "orig-work-bedroom",
  "orig-work-office",
  "orig-craft",
  "brand-monogram",
  "brand-logo",
];
