// Generated by tools/gen-images.py. Maps every ImageKey to a bundled asset URL.
// Harvested crops live in src/assets/ref/; missing crops fall back to an original asset.
import type { ImageKey } from "./image-keys";

import i_heroLiving from "@/assets/ref/hero-living.jpg";
import i_pillWood from "@/assets/ref/pill-wood.jpg";
import i_pillHandle from "@/assets/ref/pill-handle.jpg";
import i_blueprintKitchen from "@/assets/ref/blueprint-kitchen.svg";
import i_kitchenIslandFinished from "@/assets/ref/kitchen-island-finished.jpg";
import i_testimonialRoom from "@/assets/ref/testimonial-room.jpg";
import i_featuredLiving from "@/assets/ref/featured-living.jpg";
import i_gridKitchen from "@/assets/ref/grid-kitchen.jpg";
import i_gridBedroom from "@/assets/ref/grid-bedroom.jpg";
import i_gridOffice from "@/assets/ref/grid-office.jpg";
import i_gridCoveCeiling from "@/assets/ref/grid-cove-ceiling.jpg";
import i_gridFlutedTv from "@/assets/ref/grid-fluted-tv.jpg";
import i_gridIvoryKitchen from "@/assets/ref/grid-ivory-kitchen.jpg";
import i_gridKidsRoom from "@/assets/ref/grid-kids-room.jpg";
import i_gridBoutique from "@/assets/ref/grid-boutique.jpg";
import i_gridPooja from "@/assets/ref/grid-pooja.jpg";
import i_kitchenTealHero from "@/assets/ref/kitchen-teal-hero.jpg";
import i_kitchenBefore from "@/assets/ref/kitchen-before.jpg";
import i_kitchenAfter from "@/assets/ref/kitchen-after.jpg";
import i_floorPlan from "@/assets/ref/floor-plan.svg";
import i_render3d from "@/assets/ref/render-3d.jpg";
import i_elevation from "@/assets/ref/elevation.svg";
import i_matTealLaminate from "@/assets/ref/mat-teal-laminate.jpg";
import i_matBwpPlywood from "@/assets/ref/mat-bwp-plywood.jpg";
import i_matCopperHandle from "@/assets/ref/mat-copper-handle.jpg";
import i_matMarble from "@/assets/ref/mat-marble.jpg";
import i_matHinge from "@/assets/ref/mat-hinge.jpg";
import i_galleryKitchenWide from "@/assets/ref/gallery-kitchen-wide.jpg";
import i_galleryKitchenA from "@/assets/ref/gallery-kitchen-a.jpg";
import i_galleryKitchenB from "@/assets/ref/gallery-kitchen-b.jpg";
import i_galleryHandleDetail from "@/assets/ref/gallery-handle-detail.jpg";
import i_nextBedroom from "@/assets/ref/next-bedroom.jpg";
import i_isoHome from "@/assets/ref/iso-home.jpg";
import i_svcCompleteHome from "@/assets/ref/svc-complete-home.jpg";
import i_svcKitchen from "@/assets/ref/svc-kitchen.jpg";
import i_svcWardrobes from "@/assets/ref/svc-wardrobes.jpg";
import i_svcCeiling from "@/assets/ref/svc-ceiling.jpg";
import i_svcPanelling from "@/assets/ref/svc-panelling.jpg";
import i_svcRenovation from "@/assets/ref/svc-renovation.jpg";
import i_gradeStandard from "@/assets/ref/grade-standard.jpg";
import i_gradePremium from "@/assets/ref/grade-premium.jpg";
import i_gradeLuxury from "@/assets/ref/grade-luxury.jpg";
import i_cabinetInside from "@/assets/ref/cabinet-inside.jpg";
import i_planLShaped from "@/assets/ref/plan-l-shaped.svg";
import i_layoutPhoto from "@/assets/ref/layout-photo.jpg";
import i_finishPreview from "@/assets/ref/finish-preview.jpg";
import i_kitchenGallery1 from "@/assets/ref/kitchen-gallery-1.jpg";
import i_kitchenGallery2 from "@/assets/ref/kitchen-gallery-2.jpg";
import i_kitchenGallery3 from "@/assets/ref/kitchen-gallery-3.jpg";
import i_kitchenGallery4 from "@/assets/ref/kitchen-gallery-4.jpg";
import i_kitchenGallery5 from "@/assets/ref/kitchen-gallery-5.jpg";
import i_wardrobeElevation from "@/assets/ref/wardrobe-elevation.png";
import i_processMeasure from "@/assets/ref/process-measure.jpg";
import i_boardMr from "@/assets/ref/board-mr.jpg";
import i_boardBwp from "@/assets/ref/board-bwp.jpg";
import i_boardHdhmr from "@/assets/ref/board-hdhmr.jpg";
import i_boardBoilo from "@/assets/ref/board-boilo.jpg";
import i_founderPortrait from "@/assets/ref/founder-portrait.jpg";
import i_tl2014 from "@/assets/ref/tl-2014.jpg";
import i_tl2017 from "@/assets/ref/tl-2017.jpg";
import i_tl2020 from "@/assets/ref/tl-2020.jpg";
import i_tl2023 from "@/assets/ref/tl-2023.jpg";
import i_tlToday from "@/assets/ref/tl-today.jpg";
import i_wsPanelSaw from "@/assets/ref/ws-panel-saw.jpg";
import i_wsEdgeBanding from "@/assets/ref/ws-edge-banding.jpg";
import i_wsHardware from "@/assets/ref/ws-hardware.jpg";
import i_wsLaminate from "@/assets/ref/ws-laminate.jpg";
import i_wsInstall from "@/assets/ref/ws-install.jpg";
import i_team1 from "@/assets/ref/team-1.jpg";
import i_team2 from "@/assets/ref/team-2.jpg";
import i_team3 from "@/assets/ref/team-3.jpg";
import i_team4 from "@/assets/ref/team-4.jpg";
import i_team5 from "@/assets/ref/team-5.jpg";
import i_estStandard from "@/assets/ref/est-standard.jpg";
import i_estPremium from "@/assets/ref/est-premium.jpg";
import i_estLuxury from "@/assets/ref/est-luxury.jpg";
import i_workshopExterior from "@/assets/ref/workshop-exterior.jpg";
import i_livingSlatPanel from "@/assets/ref/living-slat-panel.jpg";
import i_bedroomModern from "@/assets/ref/bedroom-modern.jpg";
import i_sketchPlantLeft from "@/assets/ref/sketch-plant-left.png";
import i_sketchArchRight from "@/assets/ref/sketch-arch-right.png";
import i_journalKitchenFeatured from "@/assets/ref/journal-kitchen-featured.jpg";
import i_journalPlywood from "@/assets/ref/journal-plywood.jpg";
import i_journalCeiling from "@/assets/ref/journal-ceiling.jpg";
import i_journalWardrobeFinish from "@/assets/ref/journal-wardrobe-finish.jpg";
import i_journalWorkshop from "@/assets/ref/journal-workshop.jpg";
import i_journalWpc from "@/assets/ref/journal-wpc.jpg";
import i_journalCove from "@/assets/ref/journal-cove.jpg";
import i_avatarDinesh from "@/assets/ref/avatar-dinesh.jpg";
import i_plywoodHero from "@/assets/ref/plywood-hero.jpg";
import i_sketchPlant404 from "@/assets/ref/sketch-plant-404.png";
import i_sketchLadder404 from "@/assets/ref/sketch-ladder-404.png";
import i_sketchRoom404 from "@/assets/ref/sketch-room-404.png";
import i_catBaseUnit from "@/assets/ref/cat-base-unit.jpg";
import i_catWallUnit from "@/assets/ref/cat-wall-unit.jpg";
import i_catTallUnit from "@/assets/ref/cat-tall-unit.jpg";
import i_catLaminateSheets from "@/assets/ref/cat-laminate-sheets.jpg";
import i_catAcrylic from "@/assets/ref/cat-acrylic.jpg";
import i_catMembrane from "@/assets/ref/cat-membrane.jpg";
import i_catVeneer from "@/assets/ref/cat-veneer.jpg";
import i_catPu from "@/assets/ref/cat-pu.jpg";
import i_catTandemDrawer from "@/assets/ref/cat-tandem-drawer.jpg";
import i_catLiftUp from "@/assets/ref/cat-lift-up.jpg";
import i_catSlidingChannel from "@/assets/ref/cat-sliding-channel.jpg";
import i_catHandles from "@/assets/ref/cat-handles.jpg";
import i_catWalkIn from "@/assets/ref/cat-walk-in.jpg";
import i_catLoft from "@/assets/ref/cat-loft.jpg";
import i_catWallpaper from "@/assets/ref/cat-wallpaper.jpg";
import i_catVinylFloor from "@/assets/ref/cat-vinyl-floor.jpg";
import i_catLaminateFloor from "@/assets/ref/cat-laminate-floor.jpg";
import i_catEngineeredFloor from "@/assets/ref/cat-engineered-floor.jpg";
import i_catPopCeiling from "@/assets/ref/cat-pop-ceiling.jpg";
import i_catDesignerCeiling from "@/assets/ref/cat-designer-ceiling.jpg";
import i_catProfileLight from "@/assets/ref/cat-profile-light.jpg";
import i_catQuartz from "@/assets/ref/cat-quartz.jpg";
import i_origHeroLiving from "@/assets/hero-living.jpg";
import i_origWorkKitchen from "@/assets/work-kitchen.jpg";
import i_origWorkBedroom from "@/assets/work-bedroom.jpg";
import i_origWorkOffice from "@/assets/work-office.jpg";
import i_origCraft from "@/assets/craft.jpg";
import i_brandMonogram from "@/assets/brand/monogram.png";
import i_brandLogo from "@/assets/brand/logo-transparent.png";

export const IMAGES: Record<ImageKey, string> = {
  "hero-living": i_heroLiving,
  "pill-wood": i_pillWood,
  "pill-handle": i_pillHandle,
  "blueprint-kitchen": i_blueprintKitchen,
  "kitchen-island-finished": i_kitchenIslandFinished,
  "testimonial-room": i_testimonialRoom,
  "featured-living": i_featuredLiving,
  "grid-kitchen": i_gridKitchen,
  "grid-bedroom": i_gridBedroom,
  "grid-office": i_gridOffice,
  "grid-cove-ceiling": i_gridCoveCeiling,
  "grid-fluted-tv": i_gridFlutedTv,
  "grid-ivory-kitchen": i_gridIvoryKitchen,
  "grid-kids-room": i_gridKidsRoom,
  "grid-boutique": i_gridBoutique,
  "grid-pooja": i_gridPooja,
  "kitchen-teal-hero": i_kitchenTealHero,
  "kitchen-before": i_kitchenBefore,
  "kitchen-after": i_kitchenAfter,
  "floor-plan": i_floorPlan,
  "render-3d": i_render3d,
  elevation: i_elevation,
  "mat-teal-laminate": i_matTealLaminate,
  "mat-bwp-plywood": i_matBwpPlywood,
  "mat-copper-handle": i_matCopperHandle,
  "mat-marble": i_matMarble,
  "mat-hinge": i_matHinge,
  "gallery-kitchen-wide": i_galleryKitchenWide,
  "gallery-kitchen-a": i_galleryKitchenA,
  "gallery-kitchen-b": i_galleryKitchenB,
  "gallery-handle-detail": i_galleryHandleDetail,
  "next-bedroom": i_nextBedroom,
  "iso-home": i_isoHome,
  "svc-complete-home": i_svcCompleteHome,
  "svc-kitchen": i_svcKitchen,
  "svc-wardrobes": i_svcWardrobes,
  "svc-ceiling": i_svcCeiling,
  "svc-panelling": i_svcPanelling,
  "svc-renovation": i_svcRenovation,
  "grade-standard": i_gradeStandard,
  "grade-premium": i_gradePremium,
  "grade-luxury": i_gradeLuxury,
  "cabinet-inside": i_cabinetInside,
  "plan-l-shaped": i_planLShaped,
  "layout-photo": i_layoutPhoto,
  "finish-preview": i_finishPreview,
  "kitchen-gallery-1": i_kitchenGallery1,
  "kitchen-gallery-2": i_kitchenGallery2,
  "kitchen-gallery-3": i_kitchenGallery3,
  "kitchen-gallery-4": i_kitchenGallery4,
  "kitchen-gallery-5": i_kitchenGallery5,
  "wardrobe-elevation": i_wardrobeElevation,
  "process-measure": i_processMeasure,
  "board-mr": i_boardMr,
  "board-bwp": i_boardBwp,
  "board-hdhmr": i_boardHdhmr,
  "board-boilo": i_boardBoilo,
  "founder-portrait": i_founderPortrait,
  "tl-2014": i_tl2014,
  "tl-2017": i_tl2017,
  "tl-2020": i_tl2020,
  "tl-2023": i_tl2023,
  "tl-today": i_tlToday,
  "ws-panel-saw": i_wsPanelSaw,
  "ws-edge-banding": i_wsEdgeBanding,
  "ws-hardware": i_wsHardware,
  "ws-laminate": i_wsLaminate,
  "ws-install": i_wsInstall,
  "team-1": i_team1,
  "team-2": i_team2,
  "team-3": i_team3,
  "team-4": i_team4,
  "team-5": i_team5,
  "est-standard": i_estStandard,
  "est-premium": i_estPremium,
  "est-luxury": i_estLuxury,
  "workshop-exterior": i_workshopExterior,
  "living-slat-panel": i_livingSlatPanel,
  "bedroom-modern": i_bedroomModern,
  "sketch-plant-left": i_sketchPlantLeft,
  "sketch-arch-right": i_sketchArchRight,
  "journal-kitchen-featured": i_journalKitchenFeatured,
  "journal-plywood": i_journalPlywood,
  "journal-ceiling": i_journalCeiling,
  "journal-wardrobe-finish": i_journalWardrobeFinish,
  "journal-workshop": i_journalWorkshop,
  "journal-wpc": i_journalWpc,
  "journal-cove": i_journalCove,
  "avatar-dinesh": i_avatarDinesh,
  "plywood-hero": i_plywoodHero,
  "sketch-plant-404": i_sketchPlant404,
  "sketch-ladder-404": i_sketchLadder404,
  "sketch-room-404": i_sketchRoom404,
  "cat-base-unit": i_catBaseUnit,
  "cat-wall-unit": i_catWallUnit,
  "cat-tall-unit": i_catTallUnit,
  "cat-laminate-sheets": i_catLaminateSheets,
  "cat-acrylic": i_catAcrylic,
  "cat-membrane": i_catMembrane,
  "cat-veneer": i_catVeneer,
  "cat-pu": i_catPu,
  "cat-tandem-drawer": i_catTandemDrawer,
  "cat-lift-up": i_catLiftUp,
  "cat-sliding-channel": i_catSlidingChannel,
  "cat-handles": i_catHandles,
  "cat-walk-in": i_catWalkIn,
  "cat-loft": i_catLoft,
  "cat-wallpaper": i_catWallpaper,
  "cat-vinyl-floor": i_catVinylFloor,
  "cat-laminate-floor": i_catLaminateFloor,
  "cat-engineered-floor": i_catEngineeredFloor,
  "cat-pop-ceiling": i_catPopCeiling,
  "cat-designer-ceiling": i_catDesignerCeiling,
  "cat-profile-light": i_catProfileLight,
  "cat-quartz": i_catQuartz,
  "orig-hero-living": i_origHeroLiving,
  "orig-work-kitchen": i_origWorkKitchen,
  "orig-work-bedroom": i_origWorkBedroom,
  "orig-work-office": i_origWorkOffice,
  "orig-craft": i_origCraft,
  "brand-monogram": i_brandMonogram,
  "brand-logo": i_brandLogo,
};

export function img(key: ImageKey): string {
  return IMAGES[key];
}
