/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as HowWeBuildRouteImport } from './routes/how-we-build'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as ContactThankYouRouteImport } from './routes/contact/thank-you'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeBuildRoute = HowWeBuildRouteImport.update({
  id: '/how-we-build',
  path: '/how-we-build',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactThankYouRoute = ContactThankYouRouteImport.update({
  id: '/contact/thank-you',
  path: '/contact/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/estimator': typeof EstimatorRoute
  '/how-we-build': typeof HowWeBuildRoute
  '/contact/thank-you': typeof ContactThankYouRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/contact/': typeof ContactIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/estimator': typeof EstimatorRoute
  '/how-we-build': typeof HowWeBuildRoute
  '/contact/thank-you': typeof ContactThankYouRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/contact': typeof ContactIndexRoute
  '/journal': typeof JournalIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/estimator': typeof EstimatorRoute
  '/how-we-build': typeof HowWeBuildRoute
  '/contact/thank-you': typeof ContactThankYouRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/contact/': typeof ContactIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/estimator'
    | '/how-we-build'
    | '/contact/thank-you'
    | '/journal/$slug'
    | '/projects/$slug'
    | '/services/$slug'
    | '/contact/'
    | '/journal/'
    | '/projects/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/estimator'
    | '/how-we-build'
    | '/contact/thank-you'
    | '/journal/$slug'
    | '/projects/$slug'
    | '/services/$slug'
    | '/contact'
    | '/journal'
    | '/projects'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/estimator'
    | '/how-we-build'
    | '/contact/thank-you'
    | '/journal/$slug'
    | '/projects/$slug'
    | '/services/$slug'
    | '/contact/'
    | '/journal/'
    | '/projects/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EstimatorRoute: typeof EstimatorRoute
  HowWeBuildRoute: typeof HowWeBuildRoute
  ContactThankYouRoute: typeof ContactThankYouRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ContactIndexRoute: typeof ContactIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-build': {
      id: '/how-we-build'
      path: '/how-we-build'
      fullPath: '/how-we-build'
      preLoaderRoute: typeof HowWeBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/thank-you': {
      id: '/contact/thank-you'
      path: '/contact/thank-you'
      fullPath: '/contact/thank-you'
      preLoaderRoute: typeof ContactThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EstimatorRoute: EstimatorRoute,
  HowWeBuildRoute: HowWeBuildRoute,
  ContactThankYouRoute: ContactThankYouRoute,
  JournalSlugRoute: JournalSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ContactIndexRoute: ContactIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
